### ISSUE TITLE
How to stop infinite loop using this SDK

### ISSUE THREAD

**Issue by Davynaarscott** [smartsheet/smartsheet-javascript-sdk#13]
How can one implement this(https://smartsheet.redoc.ly/tag/webhooksDescription#section/Preventing-Infinite-Loops) using the SDK

**Comment by mattmeyerink** [comment]
Can you provide some additional details about the situation where you are running into this issue with the SDK?

**Comment by Davynaarscott** [comment]
Hi Matthew

I have included my developer, Peter, on this email so you can address this
with him.

Peter can you reply to Matthew's email below?

Thanks,

Davyn Arscott
+1-778-401-2242

**Comment by Davynaarscott** [comment]
Hi Matthew and Peter

Sorry i just realized this was an old issue that we already fixed.

Thx for following up and have a great day.
