### ISSUE TITLE
Missing response fields in getReports

### ISSUE THREAD

**Issue by chaitanya14** [smartsheet/smartsheet-javascript-sdk#24]
Hi team,

Noticed below fields are missing in [getReports](https://smartsheet.redoc.ly/tag/reports#operation/getReports). Can you please help us here ? 

**Missing response fields:**
createdAt
modifiedAt
owner
ownerId

**Comment by Scomodev** [comment]
Hey @chaitanya14,

This repo is a wrapper around the [Smartsheet API](https://smartsheet.redoc.ly/) and we will only handle issues specifically with the javascript-sdk. If you're seeing issues with data missing from the response please submit a new question on the [developers community page](https://community.smartsheet.com/categories/api-developers)

I see there was a question submitted already [there](https://community.smartsheet.com/discussion/103016/how-to-get-createdat-modifiedat-and-workspaceinfo-with-list-reports-call). I'm assuming this was you but if this hasn't solved your query please continue discussion on that thread.
