### ISSUE TITLE
Add additional URL optional parameters to getColumns

### ISSUE THREAD

**Issue by markshon** [smartsheet/smartsheet-javascript-sdk#31]
We would like to be able to provide the optional query parameters listed [here](https://smartsheet.redoc.ly/tag/columns) for the 'List Columns' method. We would like to be able to provide `includeAll` or `pageSize` and/or `page` in the 'getOptions' argument of [sheet.getColumns()](https://github.com/smartsheet/smartsheet-javascript-sdk/blob/mainline/lib/sheets/columns.js#L9).

[This line](https://github.com/smartsheet/smartsheet-javascript-sdk/blob/mainline/lib/sheets/columns.js#L30) will need to be updated to support the additional URL parameters.

**Comment by Scomodev** [comment]
These are already supported via the optional parameter `queryParameters` as part of the `getOptions`. See https://github.com/smartsheet/smartsheet-javascript-sdk/blob/mainline/ADVANCED.md#conventions

Example:
```
...sheets.getColumns({sheetId: YOUR_SHEET_ID, queryParameters: {includeAll: true}});
```
